Feature/frontendgame
ZuydUniversity/B2C6_HERKANSING_FRONTEND pull request #31
Opened 2024-08-12 13:49 UTC by Raffelke

2024-08-12 14:34 UTC, Raffelke commented
De laatste en de derde kunnen alle twee, de allerlaatste werkt dmv context/provider, terwijl bij de andere je nog los de functies (van de hooks) doorgeven in app.tsx. Bij de laatste blijft de functie van de hooks behouden en is de app.tsx veel korter.

2024-08-14 10:42 UTC, TrueProvidence commented on Zuydle/src/context/GoldContext.tsx
> +  const raiseGold = (amount: number) => {
no need to redefine an existing function right?

2024-08-14 10:44 UTC, TrueProvidence commented on Zuydle/src/context/GoldContext.tsx
> +  const [gold, setGold] = useState(1); // Initialiseer de hoeveelheid goud op 1
15, 16: these already exist. Just fetch them

2024-08-14 10:45 UTC, TrueProvidence requested changes
left comments. please use pre existing code (DRY rule)

2024-08-16 13:54 UTC, Raffelke reviewed
Frontend game works fine

2024-08-16 14:00 UTC, Raffelke commented
In een provider is het juist de bedoeling dat er een gecentraliseerd beheer is, wat het gemakkelijker maakt om iets daarin te wijzigen. Daarnaast deelt het de staat tussen de componenten en vermijdt prop drilling.

**Ik snap de comments maar dit is niet de bedoeling bij het maken van een provider!**

2024-08-18 17:43 UTC, TrueProvidence commented
> **In een provider is het juist de bedoeling dat er een gecentraliseerd beheer is**, wat het gemakkelijker maakt om iets daarin te wijzigen (en werkt ook niet bij het verwijderen van de betreffende functies). Daarnaast deelt het de staat tussen de componenten en vermijdt prop drilling.
> 
> **Ik snap de comments maar dit is niet de bedoeling bij het maken van een provider! De game mag dus zo gemerged worden naar main.** Heb code overzien maar alles klopt (zoals het nu staat).

sure Dat gecentraliseerd beheer is fine, maar ik had het erover dat de provider _nieuwe functies_ aanmaakt die gewoon van de hooks kunnen worden opgehaald. Je hebt code staan dat al ergens anders bestaat.

2024-08-18 17:47 UTC, TrueProvidence requested changes

2024-08-18 17:47 UTC, TrueProvidence commented on Zuydle/src/context/GoldContext.tsx
> +  const raiseGold = (amount: number) => {
Deze raisegold is nog steeds niet die van mijn class..

2024-08-18 17:47 UTC, TrueProvidence commented on Zuydle/src/context/GoldContext.tsx
> +    setGold((prevGold) => prevGold + amount);
Same goes for setgold

2024-08-18 17:47 UTC, TrueProvidence commented on Zuydle/src/hooks/useGold.ts
> +  const raiseGold = (amount: number) => {
tf doe je hier? Blijf van mn functie af bruv

2024-08-19 07:13 UTC, TrueProvidence approved these changes

2024-08-19 07:15 UTC, TrueProvidence commented
Unneccessarily removed my code, broke the Single Responsibility rule and ignored the Interface rule. Will accept the technical debt and slight insult in favor of progress since the project isn't moving fast enough

2024-08-19 07:15 UTC, merged

2024-08-19 17:09 UTC, Raffelke commented
Deze push besproken, alternatieve wijzen heb ik geprobeerd uit te voeren, maar op dit uitgekomen. Product is nu via deze wijze werkende zoals bedoeld. Als team nu door met de rest.